version: '3.9'
volumes:
  dados:
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: leonardo
      MYSQL_DATABASE: vxtel
      MYSQL_USER: leonardo
      MYSQL_PASSWORD: leonardo
    volumes:
      - ./mysql/init.mysql.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
  api:
    image: leonardoavelar/vxtelapi:latest
    ports:
      - 8080:80
  site:
    image: leonardoavelar/vxtelsite:latest
    ports:
      - 8081:80